import matplotlib.pyplot as plt
import numpy as np

T_gl11=np.genfromtxt("daten/gleichsinnig1.txt",usecols=0)
T_gl12=np.genfromtxt("daten/gleichsinnig1.txt",usecols=1)
T_gl1=np.concatenate([T_gl11,T_gl12])
T_gl1m=np.mean(T_gl1)
T_gl1s=np.std(T_gl1)
print('T_gl1m=', T_gl1m)
print('T_gl1s=', T_gl1s)
T_gl21=np.genfromtxt("daten/gleichsinnig2.txt",usecols=0)
T_gl22=np.genfromtxt("daten/gleichsinnig2.txt",usecols=1)
T_gl2=np.concatenate([T_gl21,T_gl22])
T_gl2m=np.mean(T_gl2)
T_gl2s=np.std(T_gl2)
print('T_gl2m=', T_gl2m)
print('T_gl2s=', T_gl2s)
########
T_gegen1=np.genfromtxt("daten/gegensinnig.txt",usecols=0)
T_gegen2=np.genfromtxt("daten/gegensinnig.txt",usecols=1)

T_gegen1m=np.mean(T_gegen1)
T_gegen1s=np.std(T_gegen1)
print('T_gegen1m=', T_gegen1m)
print('T_gegen1s=', T_gegen1s)
T_gegen2m=np.mean(T_gegen2)
T_gegen2s=np.std(T_gegen2)
print('T_gegen2m=', T_gegen2m)
print('T_gegen2s=', T_gegen2s)
#######
T_koppel1=np.genfromtxt("daten/gekoppelt1.txt",usecols=0)
Ts_koppel1=np.genfromtxt("daten/gekoppelt1.txt",skip_footer=10,usecols=1)
T_koppel2=np.genfromtxt("daten/gekoppelt2.txt",usecols=0)
Ts_koppel2=np.genfromtxt("daten/gekoppelt2.txt",skip_footer=10,usecols=1)

T_koppel1m=np.mean(T_koppel1)
T_koppel1s=np.std(T_koppel1)
print('T_koppel1m=', T_koppel1m)
print('T_koppel1s=', T_koppel1s)
T_koppel2m=np.mean(T_koppel2)
T_koppel2s=np.std(T_koppel2)
print('T_koppel2m=', T_koppel2m)
print('T_koppel2s=', T_koppel2s)

Ts_koppel1m=np.mean(Ts_koppel1)
Ts_koppel1s=np.std(Ts_koppel1)
print('Ts_koppel1m=', Ts_koppel1m)
print('Ts_koppel1s=', Ts_koppel1s)
Ts_koppel2m=np.mean(Ts_koppel2)
Ts_koppel2s=np.std(Ts_koppel2)
print('Ts_koppel2m=', Ts_koppel2m)
print('Ts_koppel2s=', Ts_koppel2s)